#ifndef _included_resource_h
#define _included_resource_h

#include "hash_table.h"
#include "text_stream_readers.h"

class Shape;
class BitmapRGBA;
class BinaryReader;
class SoundStreamDecoder;
class Resource;

class Resource
{
  protected:
    inline static unsigned int m_nameSeed = 1;

    // Bitmaps that have been registered with the resource system, so that
    // they can be used as if they had been loaded from disk or the archive.
    // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
    // can regenerate textures for them when the OpenGL context is destroyed.
    inline static HashTable<BitmapRGBA*> m_bitmaps;

    inline static HashTable<int> m_displayLists;

    inline static HashTable<int> m_textures;
    inline static HashTable<Shape*> m_shapes;

  public:
    // *** Initialisation/Destruction ***
    static void Startup() {}
    static void Shutdown();

    // *** Bitmaps ***
    static void AddBitmap(const char* _name, const BitmapRGBA& _bmp, bool _mipMapping = true);
    static const BitmapRGBA* GetBitmap(const char* _name);
    static void DeleteBitmap(const char* _name);

    // *** Textures ***
    static int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true);
    static bool DoesTextureExist(const char* _name);
    static void DeleteTexture(const char* _name);

    // *** Files ***
    static TextReader* GetTextReader(std::string_view _filename);	// Caller must delete the TextReader when done
    static BinaryReader* GetBinaryReader(const char* _filename);	// Caller must delete the BinaryReader when done

    // *** Shapes ****
    // Never produces an animatable shape because the one shape is shared between all people who call this function with the same shape name. If you want an animatable shape, call GetShapeCopy
    static Shape* GetShape(const char* _name);
    static Shape* GetShapeCopy(const char* _name, bool _animating);

    // *** Normal resources ***
    static SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename);	// Caller must delete the decoder when done

    // *** Display lists ***
    static int CreateDisplayList(const char* _name);	// Adds _name to the hashtable and calls glGenLists
    static int GetDisplayList(const char* _name);	// Returns -1 if _name doesn't exist
    static void DeleteDisplayList(const char* _name);	// Removes _name from the hashtable and calls glDeleteLists

    static void FlushOpenGlState();
    static void RegenerateOpenGlState();

    static const char* GetBaseDirectory();

    static std::vector<std::string> ListResources(const char* _dir, const char* _filter, bool _longResults = true);

    static const char* GenerateName()
    {
      auto name = new char[32];
      sprintf(name, "name_%u", m_nameSeed++);
      return name;
    }
};

#endif
