/*
 * RESOURCE SYSTEM
 *
 */

#ifndef _included_resource_h
#define _included_resource_h

#include "btree.h"
#include "llist.h"
#include "hash_table.h"

class Shape;
class BitmapRGBA;
class TextReader;
class BinaryReader;
class SoundStreamDecoder;
class Resource;
class FileWriter;

class Resource
{
  protected:
    unsigned int m_nameSeed;

    // Bitmaps that have been registered with the resource system, so that
    // they can be used as if they had been loaded from disk or the archive.
    // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
    // can regenerate textures for them when the OpenGL context is destroyed.
    HashTable<BitmapRGBA*> m_bitmaps;

    HashTable<int> m_displayLists;

    HashTable<int> m_textures;
    HashTable<Shape*> m_shapes;

    int WildCmp(const char* _wild, const char* _string);

  public:
    // *** Initialisation/Destruction ***
    Resource();
    ~Resource();

    // *** Bitmaps ***
    void AddBitmap(const char* _name, const BitmapRGBA& _bmp, bool _mipMapping = true);
    const BitmapRGBA* GetBitmap(const char* _name);
    void DeleteBitmap(const char* _name);

    // *** Textures ***
    int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true);
    bool DoesTextureExist(const char* _name);
    void DeleteTexture(const char* _name);

    // *** Files ***
    static TextReader* GetTextReader(std::string_view _filename);	// Caller must delete the TextReader when done
    static BinaryReader* GetBinaryReader(std::string_view _filename);	// Caller must delete the BinaryReader when done

    // *** Shapes ****
    Shape* GetShape(const char* _name);
    // Never produces an animatable shape because the one shape is shared between all people who call this function with the same shape name. If you want an animatable shape, call GetShapeCopy
    Shape* GetShapeCopy(const char* _name, bool _animating);

    // *** Normal resources ***
    SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename); // Caller must delete the decoder when done

    // *** Display lists ***
    int CreateDisplayList(const char* _name); // Adds _name to the hashtable and calls glGenLists
    int GetDisplayList(const char* _name); // Returns -1 if _name doesn't exist
    void DeleteDisplayList(const char* _name); // Removes _name from the hashtable and calls glDeleteLists

    void FlushRenderState();
    void RegenerateRenderState();

    char* GenerateName();

    static std::vector<std::string> ListResources(const char* _dir, const char* _filter, bool _longResults = true);
};

#endif
