#pragma once

#include "ShapeStatic.h"
#include "btree.h"
#include "hash_table.h"
#include "sound_stream_decoder.h"
#include "bitmap.h"

class Resource
{
  protected:
    inline static unsigned int m_nameSeed = {1};

    // Bitmaps that have been registered with the resource system, so that
    // they can be used as if they had been loaded from disk or the archive.
    // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
    // can regenerate textures for them when the OpenGL context is destroyed.
    inline static HashTable<BitmapRGBA*> m_bitmaps;

    inline static HashTable<int> m_displayLists;

    inline static HashTable<int> m_textures;
    inline static HashTable<ShapeStatic*> m_shapes;

    static int WildCmp(const char* _wild, const char* _string);

  public:

    // *** Bitmaps ***
      static void AddBitmap(const char* _name, const BitmapRGBA& _bmp, bool _mipMapping = true);
      static const BitmapRGBA* GetBitmap(const char* _name);
      static void DeleteBitmap(const char* _name);

    // *** Textures ***
      static int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true);
      static bool DoesTextureExist(const char* _name);
      static void DeleteTexture(const char* _name);

    // *** Files ***
    static TextReader* GetTextReader(std::string_view _filename);	// Caller must delete the TextReader when done
    static BinaryReader* GetBinaryReader(std::string_view _filename);	// Caller must delete the BinaryReader when done

    // *** Shapes ****
    static ShapeStatic* GetShapeStatic(const char* _name);

    // *** Normal resources ***
    static SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename); // Caller must delete the decoder when done

    // *** Display lists ***
    static int CreateDisplayList(const char* _name); // Adds _name to the hashtable and calls glGenLists
    static int GetDisplayList(const char* _name); // Returns -1 if _name doesn't exist
    static void DeleteDisplayList(const char* _name); // Removes _name from the hashtable and calls glDeleteLists

    static void FlushOpenGlState();
    static void RegenerateOpenGlState();

    static char* GenerateName();

    static std::vector<std::string> ListResources(const char* _dir, const char* _filter, bool _longResults = true);
};

